version: '1'

name: "sacred-garden-test"

services:

  api:
    image: krinart/sacred-garden-api:latest
    ports:
      - 8000:8000
    env_file:
    - ./.env.dev

  db:
    image: postgres:13.0-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_USER=me
    - POSTGRES_PASSWORD=me
    - POSTGRES_DB=sg
    ports:
    - 5432:5432

volumes:
  postgres_data:
