# Generated by Django 4.1.7 on 2023-04-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacred_garden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
    ]
