# Generated by Django 4.1.7 on 2023-04-10 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sacred_garden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionalLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appreciation_text', models.TextField()),
                ('text', models.TextField()),
                ('advice_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters_received_set', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters_sent_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
