# Generated by Django 4.1.7 on 2023-04-18 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sacred_garden', '0002_user_is_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionalneed',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotionalneed',
            name='sample_user_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foo', to=settings.AUTH_USER_MODEL),
        ),
    ]
