# Generated by Django 4.1.7 on 2023-03-31 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sacred_garden', '0006_emotionalneedvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionalneedvalue',
            name='partner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_emotional_need_values_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
