# Generated by Django 4.1.7 on 2023-04-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacred_garden', '0007_alter_emotionalneedvalue_partner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionalneedvalue',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
