# Generated by Django 4.1.7 on 2023-04-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacred_garden', '0008_emotionalneedvalue_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionalneedvalue',
            name='value',
            field=models.IntegerField(choices=[(0, 'Good'), (-10, 'Bad'), (-20, 'Problem')]),
        ),
    ]
