# Generated by Django 4.1.7 on 2023-04-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacred_garden', '0009_alter_emotionalneedvalue_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionalneedvalue',
            name='appreciation_text',
            field=models.TextField(default=''),
        ),
    ]
